# Generated by Django 3.2 on 2023-08-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': '评分'},
        ),
        migrations.AlterModelTable(
            name='grade',
            table='Grade',
        ),
    ]
