# Generated by Django 3.2 on 2023-08-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20230805_2025'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grade',
            table='grade',
        ),
    ]
