# Generated by Django 3.2 on 2023-08-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_alter_recommend_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='sort',
            field=models.SmallIntegerField(choices=[(1, '美食'), (2, '景点'), (0, '酒店')], default=2, verbose_name='推荐类别'),
        ),
    ]
