# Generated by Django 3.2 on 2023-08-08 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_recommend_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addinfo', to='recommend.area', verbose_name='父级的行政区域id'),
        ),
    ]
