# Generated by Django 3.2 on 2023-08-10 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_auto_20230809_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.area', verbose_name='父级的行政区域id'),
        ),
    ]
