# Generated by Django 3.2 on 2023-08-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0009_alter_area_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='pid',
            field=models.IntegerField(verbose_name='父级的行政区域id'),
        ),
    ]
