# Generated by Django 3.2 on 2023-08-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0012_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='sort',
            field=models.SmallIntegerField(choices=[(1, '美食'), (2, '景点'), (0, '住宿')], default=2, verbose_name='推荐类别'),
        ),
    ]
