# Generated by Django 3.2 on 2023-08-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0013_alter_recommend_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='rate',
            field=models.SmallIntegerField(choices=[(2, '不推荐'), (3, '推荐'), (1, '非常不推荐'), (4, '非常推荐'), (5, '极其推荐')], default=2, verbose_name='推荐指数'),
        ),
    ]
