# Generated by Django 3.2 on 2023-08-19 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0004_auto_20230812_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
