# Generated by Django 3.2 on 2023-08-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0002_rename_avatar_url_wxuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='头像', null=True, upload_to='', verbose_name='头像'),
        ),
    ]
