# Generated by Django 3.2 on 2023-08-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0006_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='info',
        ),
    ]
