# Generated by Django 3.2 on 2023-08-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0007_rename_feedback_feedback_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
