# Generated by Django 3.2 on 2023-08-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0009_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
