# Generated by Django 3.2 on 2023-08-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0013_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, '男'), (1, '女'), (2, '未知')], help_text='性别', null=True, verbose_name='性别'),
        ),
    ]
