# Generated by Django 3.2 on 2023-08-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0014_alter_wxuser_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='wxuser',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
